apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vx6o
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hxka-tenant/rhtap-demo-app/hacbs-test-project-vx6o@sha256:00eb089f34e6ac2ee4def5da355a263797106b04dfa0e5ceb679d13f59abf4ef
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
